context_loader:
  csv_args:
    delimiter: ','
    quotechar: '"'
  file_path: /home/yfg2/Multimodal-RAG/data/context_metadata/processed_eng_context_metadata/processed_2016_02_english.csv
  metadata_columns:
  - lan
  - src
  - dur
  - col
  - path
  type: CSVLoader
dataloader:
  batch_size: 8
  shuffle: false
dataset:
  file: data/QA/format_QAdata_small.json
  language: en
evaluation:
  metrics:
  - context_recall
  - context_precision
  - answer_correctness
  - answer_relevancy
guardrails:
  config_path: guardrails_config
llm:
  batch_size: 1
  device_map: auto
  do_sample: true
  max_new_tokens: 1024
  model_id: microsoft/Phi-3-mini-4k-instruct
  repetition_penalty: 1.0
  return_full_text: false
  task: text-generation
  temperature: 0.1
  use_endpoint: true
prompt:
  fine_tuned_rag: 'You are an assistant for question-answering tasks. Use the following
    pieces of retrieved context to answer the question. If you don''t know the answer,
    just say that you don''t know. Use three sentences maximum and keep the answer
    concise.


    Question: {question}


    Context: {context}


    Answer:"

    '
  fine_tuned_without_rag: 'You are an assistant for question-answering tasks. If you
    don''t know the answer, just say that you don''t know. Keep the answer concise.


    Question: {question}


    Answer:"

    '
  input_variables_rag:
  - question
  - context
  input_variables_without_rag:
  - question
  template_en_rag: 'You are an assistant for question-answering tasks. Use the following
    pieces of retrieved context to answer the question. If you don''t know the answer,
    just say that you don''t know. Use three sentences maximum and keep the answer
    concise.


    Question: {question}


    Context: {context}


    Answer:

    '
  template_en_without_rag: 'You are an assistant for question-answering tasks. If
    you don''t know the answer, just say that you don''t know. Keep the answer concise.


    Question: {question}


    Answer:

    '
  template_fr_rag: "Vous \xEAtes un assistant pour les t\xE2ches de question-r\xE9\
    ponse. Utilisez les morceaux de contexte suivants pour r\xE9pondre \xE0 la question.\
    \ Si vous ne connaissez pas la r\xE9ponse, dites simplement que vous ne savez\
    \ pas. Utilisez trois phrases maximum et gardez la r\xE9ponse concise.\n\nQuestion:\
    \ {question}\n\nContexte: {context}\n\nR\xE9ponse:\n"
  template_fr_without_rag: "Vous \xEAtes un assistant pour les t\xE2ches de question-r\xE9\
    ponse. Si vous ne connaissez pas la r\xE9ponse, dites simplement que vous ne savez\
    \ pas. Gardez la r\xE9ponse concise.\n\nQuestion: {question}\n\nR\xE9ponse:\n"
use_guardrails: true
use_rag: true
vectordb:
  create_new_collection: true
  embedding_function:
    model_kwargs:
      device: 0
    model_name: sentence-transformers/all-mpnet-base-v2
  qdrant:
    collection_name: english_2016_02
    path: data/db_english_2016_02
  splitter:
    chunk_overlap: 150
    chunk_size: 756
    type: RecursiveCharacterTextSplitter
